version: 2.0

jobs:
  autofix-workspace-images:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            echo "Hello world"

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - autofix-workspace-images
