version: 2.0

jobs:
  autofix-workspace-images:
    docker:
      - image: gitpod/workspace-full:latest
    steps:
      - run:
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            pip install codespell
            npm install -g autofix
            git clone --recurse-submodules https://github.com/gitpod-io/workspace-images
            cd workspace-images
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN --pull-request
            cd ..
            git clone --recurse-submodules https://github.com/jankeromnes/submodule-poc
            cd submodule-poc
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN --pull-request
            cd ..
            git clone --recurse-submodules https://github.com/eclipse-theia/theia
            cd theia
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --signoff --push=$GITHUB_LOGIN
            cd ..
            git clone --recurse-submodules https://github.com/mozilla/gecko-dev
            cd gecko-dev
            hub fork
            autofix --branches --branch-suffix=$CIRCLE_BUILD_NUM --push=$GITHUB_LOGIN
            cd ..
          no_output_timeout: 120m

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "40 11 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - autofix-workspace-images
