version: 2.0

jobs:
  autofix-workspace-images:
    docker:
      - image: gitpod/workspace-full:latest
    steps:
      - run:
          command: |
            set -e
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            git clone https://github.com/gitpod-io/workspace-images
            cd workspace-images
            npm install -g autofix
            hub fork
            autofix --branches --push=$GITHUB_LOGIN

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "5 3 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - autofix-workspace-images
