version: 2.0

jobs:
  autofix-workspace-images:
    docker:
      - image: gitpod/workspace-full:latest
    steps:
      - checkout
      - run:
          command: |
            ./.circleci/setup.sh
            git clone https://github.com/gitpod-io/workspace-images
            cd workspace-images
            hub fork
            autofix --branches --push=$GITHUB_LOGIN --pull-request

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 16 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - autofix-workspace-images
